version: '3'
services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    command: yarn start
    depends_on:
      - mongodb
    volumes:
      - .:/src
      - /node_modules
    ports:
      - 80:3000
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
